In [3]:
import numpy as np

In [4]:
arr = np.array([[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9]])
arr

array([[1, 2, 3, 4, 5],
       [2, 4, 5, 6, 7],
       [5, 7, 8, 9, 9]])

In [39]:
lst = [[1,2,3,4,5],[2,4,5,6,7],[5,7,8,9,9]]
r = [i[3:]for i in lst[1:]]
r

[[6, 7], [9, 9]]

In [15]:
arr[1:,3:]

array([[6, 7],
       [9, 9]])

In [50]:
arr.astype('float64')

array([[1., 2., 3., 4., 5.],
       [2., 4., 5., 6., 7.],
       [5., 7., 8., 9., 9.]])

In [59]:
cf = np.array([-750,-250,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100])
def npvCal(year, discount):
    npv = 0
    for i in range(year):
        npv += cf[i]/((discount+1)**(i+1))
    return npv
npv = npvCal(20,0.1)
npv


-210.6270990985242

In [1]:
import pandas as pd

In [75]:
data = {
    'name' : ['John', 'Doe', 'Jane','Chris'],
    'age' : [21,22,33,44],
    'score' : [79,98,86,70]
}

In [78]:
df = pd.read_csv('apt.csv', encoding='cp949');
df.head(3)

지역   번지   본번  부번           아파트       면적    계약년월  계약일     가격   층  \
0  강원도 강릉시 견소동  202  202   0          송정한신   59.800  201910    4  10900   5   
1  강원도 강릉시 견소동  202  202   0          송정한신  116.175  201910   31  18500  10   
2  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910    5  25000   6   

   건축년도           도로명  
0  1997   경강로2539번길 8  
1  1997   경강로2539번길 8  
2  2005  경강로2539번길 22

In [80]:
df.shape

(42758, 12)

In [87]:
df[df['가격']>40000][['가격','면적','지역']].sort_values(by = '면적', ascending=False)

가격        면적               지역
35826  300000  291.3360    인천광역시 연수구 송도동
31501  240000  273.8200     서울특별시 중구 신당동
10106  100000  244.6630    경기도 용인수지구 성복동
30002  206000  244.4200    서울특별시 서초구 서초동
27118  245000  242.8200    서울특별시 강남구 역삼동
...       ...       ...              ...
29725   43500   30.0100    서울특별시 마포구 아현동
27124   74000   28.2460    서울특별시 강남구 역삼동
27123   76000   28.2460    서울특별시 강남구 역삼동
27122   74500   28.2460    서울특별시 강남구 역삼동
30111   90000   25.3284  서울특별시 성동구 성수동1가

[10486 rows x 3 columns]

In [4]:
df = pd.read_csv('survey.csv', encoding='cp949');
df.head(5)

sex  income  English  jobSatisfaction  stress
0   m    3000      500                5       5
1   f    4000      600                4       4
2   f    5000      700                3       2
3   m    6000      800                2       2
4   m    4000      700                2       5

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   sex              23 non-null     object
 1   income           23 non-null     int64 
 2   English          23 non-null     int64 
 3   jobSatisfaction  23 non-null     int64 
 4   stress           23 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 1.0+ KB


In [16]:
df = pd.read_csv('apt.csv', encoding='cp949');
df.head(3)

지역   번지   본번  부번           아파트       면적    계약년월  계약일     가격   층  \
0  강원도 강릉시 견소동  202  202   0          송정한신   59.800  201910    4  10900   5   
1  강원도 강릉시 견소동  202  202   0          송정한신  116.175  201910   31  18500  10   
2  강원도 강릉시 견소동  289  289   0  송정해변신도브래뉴아파트   84.990  201910    5  25000   6   

   건축년도           도로명  
0  1997   경강로2539번길 8  
1  1997   경강로2539번길 8  
2  2005  경강로2539번길 22

In [19]:
df[df['가격'] >= 40000][['가격','면적','지역']].sort_values(by = '면적', ascending=True)

가격        면적               지역
30111   90000   25.3284  서울특별시 성동구 성수동1가
27124   74000   28.2460    서울특별시 강남구 역삼동
27123   76000   28.2460    서울특별시 강남구 역삼동
27122   74500   28.2460    서울특별시 강남구 역삼동
29725   43500   30.0100    서울특별시 마포구 아현동
...       ...       ...              ...
27118  245000  242.8200    서울특별시 강남구 역삼동
30002  206000  244.4200    서울특별시 서초구 서초동
10106  100000  244.6630    경기도 용인수지구 성복동
31501  240000  273.8200     서울특별시 중구 신당동
35826  300000  291.3360    인천광역시 연수구 송도동

[10691 rows x 3 columns]

In [33]:
df.loc[df['가격'] >= 40000, ['가격', '면적','지역']].sort_values(by = '면적', ascending=False)

가격        면적               지역
35826  300000  291.3360    인천광역시 연수구 송도동
31501  240000  273.8200     서울특별시 중구 신당동
10106  100000  244.6630    경기도 용인수지구 성복동
30002  206000  244.4200    서울특별시 서초구 서초동
27118  245000  242.8200    서울특별시 강남구 역삼동
...       ...       ...              ...
29725   43500   30.0100    서울특별시 마포구 아현동
27122   74500   28.2460    서울특별시 강남구 역삼동
27123   76000   28.2460    서울특별시 강남구 역삼동
27124   74000   28.2460    서울특별시 강남구 역삼동
30111   90000   25.3284  서울특별시 성동구 성수동1가

[10691 rows x 3 columns]

In [3]:
from scipy import stats

In [5]:
df.corr(numeric_only=True)

income   English  jobSatisfaction    stress
income           1.000000  0.599452        -0.040108 -0.137920
English          0.599452  1.000000        -0.312051  0.073351
jobSatisfaction -0.040108 -0.312051         1.000000  0.165338
stress          -0.137920  0.073351         0.165338  1.000000

In [6]:
import statsmodels.formula.api as smf

In [8]:
model = smf.ols(formula='jobSatisfaction~English+stress+income', data = df)
result = model.fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:        jobSatisfaction   R-squared:                       0.187
Model:                            OLS   Adj. R-squared:                  0.059
Method:                 Least Squares   F-statistic:                     1.458
Date:                Thu, 13 Jun 2024   Prob (F-statistic):              0.258
Time:                        12:06:33   Log-Likelihood:                -35.038
No. Observations:                  23   AIC:                             78.08
Df Residuals:                      19   BIC:                             82.62
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.9159      1.712      2.871      0.010       1.333       8.499
English       -0.0064      0.003     -1.931      0.069      -0.013       0.001
stress         0.2141      0.187      1.145      0.266      -0.177       0.606
income         0.0004      0.000      1.125      0.275      -0.000       0.001
==============================================================================
Omnibus:                        0.278   Durbin-Watson:                   0.989
Prob(Omnibus):                  0.870   Jarque-Bera (JB):                0.457
Skew:                          -0.036   Prob(JB):                        0.796
Kurtosis:                       2.313   Cond. No.                     3.00e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large,  3e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""